src/main/java/com/thoughtworks/videorental/domain/ClassicMovieChargingStrategy.java
package com.thoughtworks.videorental.domain;

public class ClassicMovieChargingStrategy implements MovieChargingStrategy {
    @Override
    public Double getPrice(int days) {
        double perDayCharge = 0.5;
        double weeklyCharge = 3.0;

        if (days < 7) {
            return days * perDayCharge;
        }
        if (days == 7) {
            return weeklyCharge;
        }
        return perDayCharge + getPrice(days - 1);

    }
}

src/main/java/com/thoughtworks/videorental/domain/Customer.java
package com.thoughtworks.videorental.domain;

import lombok.EqualsAndHashCode;

import java.security.Principal;
import java.util.Set;

@EqualsAndHashCode
public class Customer implements Principal{
    private String name;

    public Customer(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public String statement(final Set<Rental> newRentals) {
        String result = "Rental Record for " + getName() + "\n";

        double totalAmount = 0;
        for (Rental rental : newRentals) {
            // show figures for this rental

            result += "  " + rental.getMovie().getTitle() + "  -  $"
                    + String.valueOf(rental.getCharge()) + "\n";

            totalAmount += rental.getCharge();
        }

        // add footer lines
        result += "Amount charged is $" + String.valueOf(totalAmount);
        return result;
    }
}

src/main/java/com/thoughtworks/videorental/domain/DefaultMoviePricingStrategy.java
package com.thoughtworks.videorental.domain;

public class DefaultMoviePricingStrategy implements MovieChargingStrategy {
    @Override
    public Double getPrice(int days) {
        return days * 1.0;
    }
}

src/main/java/com/thoughtworks/videorental/domain/Movie.java
package com.thoughtworks.videorental.domain;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class Movie {
    private MovieType type;
    private String title;

    public Movie(String title, MovieType type) {
        this.title = title;
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public MovieType getType() {
        return type;
    }
}

src/main/java/com/thoughtworks/videorental/domain/MovieChargingStrategy.java
package com.thoughtworks.videorental.domain;

public interface MovieChargingStrategy {
    Double getPrice(int days);
}

src/main/java/com/thoughtworks/videorental/domain/MovieChargingStrategyFactory.java
package com.thoughtworks.videorental.domain;

public class MovieChargingStrategyFactory {

    public static MovieChargingStrategy getStrategyFor(MovieType type) {
        switch (type) {
            case CLASSIC:
                return new ClassicMovieChargingStrategy();
            case NEW:
                return new NewMovieChargingStrategy();
            case DEFAULT:
            default:
                return new DefaultMoviePricingStrategy();
        }
    }
}

src/main/java/com/thoughtworks/videorental/domain/MovieType.java
package com.thoughtworks.videorental.domain;

/**
 * Created by ashutoshraina on 12/02/15.
 */
public enum MovieType {
    DEFAULT, CLASSIC, NEW
}

src/main/java/com/thoughtworks/videorental/domain/NewMovieChargingStrategy.java
package com.thoughtworks.videorental.domain;

public class NewMovieChargingStrategy implements MovieChargingStrategy {
    @Override
    public Double getPrice(int days) {
        Double totalCharge = 0.0;

        if (days < 2) {
            totalCharge += 3;
        } else {
            totalCharge += 3 + extendedPeriod(days) * 2;
        }

        return totalCharge;
    }
    private int extendedPeriod(int days) {
        return days - 2;
    }

}

src/main/java/com/thoughtworks/videorental/domain/Rental.java
package com.thoughtworks.videorental.domain;

import lombok.EqualsAndHashCode;
import org.joda.time.LocalDateTime;
import org.joda.time.Period;

@EqualsAndHashCode
public class Rental {
    private final Movie movie;
    private final Customer customer;
    private final LocalDateTime rentedOn;
    private final Period period;

    public Rental(Customer customer, Movie movie, Period period, LocalDateTime rentedOn) {
        this.movie = movie;
        this.customer = customer;
        this.period = period;
        this.rentedOn = rentedOn;
    }

    public Movie getMovie() {
        return movie;
    }

    public Customer getCustomer() {
        return customer;
    }

    public Period getPeriod() {
        return period;
    }

    public LocalDateTime getRentedOn() {
        return rentedOn;
    }

    public LocalDateTime getEndDate() {
        return rentedOn.plus(period);
    }

    public Double getCharge() {
        int days = period.getDays();
        MovieChargingStrategy chargingStrategy = MovieChargingStrategyFactory.getStrategyFor(movie.getType());
        return chargingStrategy.getPrice(days);
    }

    public int getPoints() {
        if(movie.getType() == MovieType.NEW){
            return period.getDays() * 2;
        }
        return getCharge().intValue();
    }
}

src/main/java/com/thoughtworks/videorental/domain/Transaction.java
package com.thoughtworks.videorental.domain;

import lombok.EqualsAndHashCode;
import org.joda.time.LocalDateTime;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

@EqualsAndHashCode
public class Transaction {
    private final LocalDateTime dateTime;
    private final Customer customer;
    private final Set<Rental> rentals;

    public Transaction(final LocalDateTime dateTime, final Customer customer, final Set<Rental> rentals) {
        this.dateTime = dateTime;
        for (final Rental rental : rentals) {
            if (!rental.getCustomer().equals(customer)) {
                throw new IllegalArgumentException("Rentals must be for the same customer");
            }
        }
        this.customer = customer;
        this.rentals = Collections.unmodifiableSet(new HashSet<Rental>(rentals));
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public Customer getCustomer() {
        return customer;
    }

    public Set<Rental> getRentals() {
        return rentals;
    }
}

src/main/java/com/thoughtworks/videorental/domain/repository/CustomerRepository.java
package com.thoughtworks.videorental.domain.repository;

import com.thoughtworks.videorental.domain.Customer;
import com.thoughtworks.videorental.domain.specification.Specification;

import java.util.Collection;
import java.util.Comparator;
import java.util.Set;

public interface CustomerRepository {
    void add(Customer entity) throws NullObjectAddedException;

    void add(Collection<Customer> entities) throws NullObjectAddedException;

    Set<Customer> selectAll();

    Set<Customer> selectAll(Comparator<Customer> comparator);

    Set<Customer> selectSatisfying(Specification<Customer> specification);

    Set<Customer> selectSatisfying(Specification<Customer> specification, Comparator<Customer> comparator);

    Customer selectUnique(Specification<Customer> specification) throws NonUniqueObjectSelectedException;
}

src/main/java/com/thoughtworks/videorental/domain/repository/MovieRepository.java
package com.thoughtworks.videorental.domain.repository;

import com.thoughtworks.videorental.domain.Movie;
import com.thoughtworks.videorental.domain.specification.Specification;

import java.util.Collection;
import java.util.Comparator;
import java.util.Set;

public interface MovieRepository {
    void add(Movie entity) throws NullObjectAddedException;

    void add(Collection<Movie> entities) throws NullObjectAddedException;

    Set<Movie> selectAll();

    Set<Movie> selectAll(Comparator<Movie> comparator);

    Set<Movie> selectSatisfying(Specification<Movie> specification);

    Set<Movie> selectSatisfying(Specification<Movie> specification, Comparator<Movie> comparator);

    Movie selectUnique(Specification<Movie> specification) throws NonUniqueObjectSelectedException;

    Set<Movie> withTitles(String... titles);
}

src/main/java/com/thoughtworks/videorental/domain/repository/NonUniqueObjectSelectedException.java
package com.thoughtworks.videorental.domain.repository;

public class NonUniqueObjectSelectedException extends Exception {
    public NonUniqueObjectSelectedException() {
    }

    public NonUniqueObjectSelectedException(final Exception cause) {
        super(cause);
    }

}

src/main/java/com/thoughtworks/videorental/domain/repository/NullObjectAddedException.java
package com.thoughtworks.videorental.domain.repository;

public class NullObjectAddedException extends RuntimeException {
}

src/main/java/com/thoughtworks/videorental/domain/repository/RentalRepository.java
package com.thoughtworks.videorental.domain.repository;

import com.thoughtworks.videorental.domain.Customer;
import com.thoughtworks.videorental.domain.Rental;
import com.thoughtworks.videorental.domain.specification.Specification;

import java.util.Collection;
import java.util.Comparator;
import java.util.Set;

public interface RentalRepository {
    void add(Rental entity) throws NullObjectAddedException;

    void add(Collection<Rental> entities) throws NullObjectAddedException;

    Set<Rental> selectAll();

    Set<Rental> selectAll(Comparator<Rental> comparator);

    Set<Rental> selectSatisfying(Specification<Rental> specification);

    Set<Rental> selectSatisfying(Specification<Rental> specification, Comparator<Rental> comparator);

    Rental selectUnique(Specification<Rental> specification) throws NonUniqueObjectSelectedException;

    Set<Rental> currentRentalsFor(Customer customer);
}

src/main/java/com/thoughtworks/videorental/domain/repository/SetBasedRepository.java
package com.thoughtworks.videorental.domain.repository;


import com.thoughtworks.videorental.domain.specification.Specification;

import java.util.*;

public class SetBasedRepository<T> {
    private final Set<T> objectSet;

    public SetBasedRepository() {
        objectSet = new HashSet<T>();
    }

    public SetBasedRepository(final Collection<T> entities) {
        objectSet = new HashSet<T>(entities);
    }

    public void add(final T entity) throws NullObjectAddedException {
        if (entity == null) {
            throw new NullObjectAddedException();
        }
        objectSet.add(entity);
    }

    public void add(final Collection<T> entities) throws NullObjectAddedException {
        if (entities == null) {
            throw new IllegalArgumentException();
        }
        for (final T entity : entities) {
            if (entity == null) {
                throw new NullObjectAddedException();
            }
        }
        objectSet.addAll(entities);
    }

    public Set<T> selectAll() {
        return new HashSet<T>(objectSet);
    }

    public Set<T> selectAll(final Comparator<T> comparator) {
        final List<T> result = new ArrayList<T>(objectSet);
        Collections.sort(result, comparator);
        return new LinkedHashSet<T>(result);
    }

    public Set<T> selectSatisfying(final Specification<T> specification) {
        return selectSatisfyingIntoCollection(specification, new HashSet<T>());
    }

    public Set<T> selectSatisfying(final Specification<T> specification, final Comparator<T> comparator) {
        final List<T> result = selectSatisfyingIntoCollection(specification, new ArrayList<T>());
        Collections.sort(result, comparator);
        return new LinkedHashSet<T>(result);
    }

    public T selectUnique(final Specification<T> specification) throws NonUniqueObjectSelectedException {
        final List<T> results = selectSatisfyingIntoCollection(specification, new ArrayList<T>());
        if (results.size() == 1) {
            return results.get(0);
        } else if (!results.isEmpty()) {
            throw new NonUniqueObjectSelectedException();
        }
        return null;
    }

    private <C extends Collection<T>> C selectSatisfyingIntoCollection(final Specification<T> specification,
                                                                       final C target) {
        for (T object : objectSet) {
            if (specification.isSatisfiedBy(object)) {
                target.add(object);
            }
        }
        return target;
    }
}

src/main/java/com/thoughtworks/videorental/domain/repository/TransactionRepository.java
package com.thoughtworks.videorental.domain.repository;

import com.thoughtworks.videorental.domain.Customer;
import com.thoughtworks.videorental.domain.Transaction;
import com.thoughtworks.videorental.domain.specification.Specification;

import java.util.Collection;
import java.util.Comparator;
import java.util.Set;

public interface TransactionRepository {
    void add(Transaction entity) throws NullObjectAddedException;

    void add(Collection<Transaction> entities) throws NullObjectAddedException;

    Set<Transaction> selectAll();

    Set<Transaction> selectAll(Comparator<Transaction> comparator);

    Set<Transaction> selectSatisfying(Specification<Transaction> specification);

    Set<Transaction> selectSatisfying(Specification<Transaction> specification, Comparator<Transaction> comparator);

    Transaction selectUnique(Specification<Transaction> specification) throws NonUniqueObjectSelectedException;

    Collection<Transaction> transactionsBy(Customer customer);
}

src/main/java/com/thoughtworks/videorental/domain/specification/AndSpecification.java
package com.thoughtworks.videorental.domain.specification;


import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

public class AndSpecification<T> implements Specification<T> {
    private final List<Specification<T>> subSpecifications;

    public <S extends Specification<T>> AndSpecification(final Collection<S> specifications) {
        subSpecifications = new ArrayList<Specification<T>>(specifications);
    }

    public AndSpecification(final Specification<T>... specifications) {
        subSpecifications = Arrays.asList(specifications);
    }

    public boolean isSatisfiedBy(final T object) {
        for (final Specification<T> specification : subSpecifications) {
            if (!specification.isSatisfiedBy(object)) {
                return false;
            }
        }
        return true;
    }

    @Override
    @SuppressWarnings("unchecked")
    public boolean equals(final Object obj) {
        if (!(obj instanceof AndSpecification)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        final AndSpecification other = (AndSpecification) obj;
        return CollectionUtils.isEqualCollection(subSpecifications, other.subSpecifications);
    }

    @Override
    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new HashCodeBuilder();
        for (final Specification<T> specification : subSpecifications) {
            hashCodeBuilder.append(specification);
        }
        return hashCodeBuilder.toHashCode();
    }
}

src/main/java/com/thoughtworks/videorental/domain/specification/CurrentRentalSpecification.java
package com.thoughtworks.videorental.domain.specification;


import com.thoughtworks.videorental.domain.Rental;
import org.joda.time.LocalDateTime;

public class CurrentRentalSpecification implements Specification<Rental> {

    @Override
    public boolean isSatisfiedBy(final Rental rental) {
        return !rental.getEndDate().isBefore(new LocalDateTime());
    }

}

src/main/java/com/thoughtworks/videorental/domain/specification/CustomerWithNameSpecification.java
package com.thoughtworks.videorental.domain.specification;


import com.thoughtworks.videorental.domain.Customer;

public class CustomerWithNameSpecification implements Specification<Customer> {

    private final String customerName;

    public CustomerWithNameSpecification(final String customerName) {
        this.customerName = customerName;
    }

    @Override
    public boolean isSatisfiedBy(final Customer customer) {
        return customer.getName().equals(customerName);
    }


}

src/main/webapp/admin.ftl
<html>
<head>
    <title>Administration</title>
    <#include "includes/common.ftl">
</head>
<body>
    <#include "includes/header.ftl"/>
    <h1>Customers</h1>
    <ul>
	<#list users as user>
	<li>${user.name}</li>
	</#list>
	</ul>
    <#include "includes/footer.ftl"/>
</body>
</html>

src/main/webapp/history.ftl
<html>
<head>
    <#include "includes/common.ftl"/>
    <title>Transaction History</title>
</head>
<body>
    <#include "includes/header.ftl"/>

    <h1>Transaction History</h1>
    <ul>
    <#list transactions as transaction>
    	<li>Transaction on ${transaction.dateTime}<br />
    	Movies Rented:
		<#list transaction.rentals as rental>
			${rental.movie.title}<#if rental_has_next>, </#if>
		</#list>
		</li>
	</#list>
	</ul>
    <#include "includes/footer.ftl"/>

</body>
</html>

src/main/webapp/home.ftl
<html>
<head>
    <#include "includes/common.ftl"/>
    <title>Rent a Movie</title>
    <link href="styles/wizard.css" rel="stylesheet" type="text/css"></link>
    <script type="text/javascript" src="js/wizard.js"></script>
    <script type="text/javascript">
	$(function() {
	    $('#wizard').wizard({
	    	validate: function(idx, elem) {
	    		switch(idx) {
	    			case 0:
	    				if ($('input[name=movieNames]:checked').size() == 0) {
	    					alert('Please select at least one movie');
	    					return false;
	    				}
	    				return true;
	    			case 2:
	    				if ($('input[name=customerName]:checked').size() != 1) {
	    					alert('Please select a customer');
	    					return false;
	    				}
	    				return true;
	    			default:
	    				return true;
	    		}
	    	}
	    });
	}); 
  </script>
</head>
<body>
    <#include "includes/header.ftl"/>
    <h1>Rent a Movie</h1>
	<form id="wizard" class="wiz-container" action="rentals" method="post">
		<ul class="wiz-list">
			<li><a href="#wizard-1">
				<h2>Now Showing!</h2>
				<small>Pick a movie</small>
			</a></li>
			<li><a href="#wizard-2"><h2>How long for?</h2>
				<small>Tell us how many days you want to rent for</small>
			</a></li>
		</ul>
		<div class="wiz-body">
			<div id="wizard-1">
				<div class="wiz-content movielist">					
			    	<#list movies as movie>
			    		<div class="movie">
			    			<p><input type="checkbox" name="movieNames" value="${movie.title}"/> ${movie.title}</p>
			    		</div>
			    	</#list>
				</div>
				<div class="wiz-nav">
					<input class="back btn" type="button" value="< Prev" />
					<input class="next btn" type="button" value="Next >" />
				</div>
			</div>
			<div id="wizard-2">
				<div class="wiz-content">					
					<p>Number of days:
						<select name="rentalDuration">
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
						</select>
					</p>
				</div>
				<div class="wiz-nav">
					<input class="back btn" type="button" value="< Prev" />
					<input class="done btn" type="submit" value="Done" />
				</div>
			</div>
		</div>
	</form>
    <#include "includes/footer.ftl"/>
</body>
</html>

src/main/webapp/login.ftl
<html>
<head>
    <title>Login</title>
    <#include "includes/common.ftl"/>
</head>
<body>
    <h1>Login</h1>
	<form id="login" method="post">
	    <p>Select user:</p>
		<select class="customer" name="username">
	    	<#list customers as customer>
	    	<option value="${customer.name}">${customer.name}</option>
	    	</#list>
		</select>
    	<input type="submit" value="login" />
	</form>
    <#include "includes/footer.ftl"/>
</body>
</html>

src/main/webapp/rentals.ftl
<html>
<head>
    <#include "includes/common.ftl"/>
<title>Current Rentals</title>
</head>
<body>
<#include "includes/header.ftl"/>

<h1>Current Rentals</h1>
<ul>
<#list rentals as rental>
    <li>${rental.movie.title} (ends ${rental.endDate})</li>
</#list>
</ul>
<#include "includes/footer.ftl"/>
</body>
</html>

src/main/webapp/statement.ftl
<html>
<head>
    <#include "includes/common.ftl"/>
    <title>Rental Statement</title>
</head>
<body>
    <#include "includes/header.ftl"/>
    <h1>Rental Statement</h1>
    <pre>${statement}</pre>
    <#include "includes/footer.ftl"/>
</body>
</html>